---
title: "exploration"
format: html
---

# Setup

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(sf)
#library(sfheaders)
library(arrow)
library(duckdb)
```

# Loading Data

## Geodaten von Gisco

```{r}
gemeinden <- giscoR::gisco_get_communes(epsg = "3035", country = "DE")
darmstadt <- gemeinden %>% filter(COMM_NAME == "Darmstadt")
berlin <- gemeinden %>% filter(COMM_NAME == "Berlin")
# Hamburg hat zwei Exklaven die ich hier entferne
hamburg <- gemeinden %>% 
  filter(COMM_NAME == "Hamburg") %>%
  st_cast("POLYGON") %>%
  mutate(area = st_area(.)) %>%
  slice_max(area, n = 1) %>%
  st_cast("MULTIPOLYGON")
```

## Breitbandatlas

```{r}
# Laden der Arrow Datensätze
breitband_100m_arrow <- open_dataset("./Daten/Breitbandatlas/Raster_100m/")
breitband_1km_arrow <- open_dataset("./Daten/Breitbandatlas/Raster_1km/")

# Funktion um automatisch Daten einer bestimmen Stadt zu laden
get_breitband_stadt <- function(stadt_name, size = "100m", variables = everything()) {
  stadt <- gemeinden %>% 
    filter(COMM_NAME == stadt_name) %>%
    st_cast("POLYGON") %>%
    mutate(area = st_area(.)) %>%
    slice_max(area, n = 1) %>%
    st_cast("MULTIPOLYGON")
  
  if(size == "100m") {
    breitband_100m_arrow %>%
      select(date, x_mp, y_mp, {{variables}}) %>%
      filter(x_mp %>% between(st_bbox(stadt)["xmin"], st_bbox(stadt)["xmax"]),
             y_mp %>% between(st_bbox(stadt)["ymin"], st_bbox(stadt)["ymax"])) %>%
      collect()
  } else if(size == "1km") {
    breitband_1km_arrow %>%
      select(date, x_mp, y_mp, {{variables}}) %>%
      filter(x_mp %>% between(st_bbox(stadt)["xmin"], st_bbox(stadt)["xmax"]),
           y_mp %>% between(st_bbox(stadt)["ymin"], st_bbox(stadt)["ymax"])) %>%
      collect()
  }
}

# Beispielabfrage
breitband_glasfaser_berlin <- get_breitband_stadt("Berlin", size = "100m", variables = down_fn_hh_ftthb_1000)
```

## Zensusdaten

```{r}
zensus_arrow <- open_dataset("./Daten/Zensus/Gesamt/")

zensus_beispiel <- zensus_arrow %>%
  filter(typ == "100m") %>%
  select(x_mp, y_mp, insgesamt_bevoelkerung, durchschnittsalter, eigentuemerquote, durchschn_miete_qm) %>%
  collect()

zensus_einwohner_100m <- zensus_arrow %>%
  filter(typ == "100m") %>%
  select(x_mp, y_mp, durchschn_hh_groesse, insgesamt_bevoelkerung) %>%
  mutate(anzahl_haushalte = insgesamt_bevoelkerung / durchschn_hh_groesse) %>%
  collect()
```

## LAEA Grid

```{r}

```

# Funktion um Grid zu erstellen

Erstelle Grid zu sf Objekt
```{r}
make_laea_grid <- function(obj, size = 100) {
  obj_bbox <- st_bbox(obj)
  obj_offset_x <- floor(obj_bbox["xmin"]/size)*size - (size/2)
  obj_offset_y <- floor(obj_bbox["ymin"]/size)*size - (size/2)
  
  st_make_grid(obj, cellsize = size, offset = c(obj_offset_x, obj_offset_y))
}

# Beispiel
darmstadt %>%
  make_laea_grid(size = 1000) %>%
  ggplot()+
  geom_sf()+
  geom_sf(data = darmstadt, fill = NA)
```

Füge Grid zu Daten hinzu
```{r}
add_laea_grid <- function(obj, size = 100, x_mp = "x_mp", y_mp = "y_mp") {
  obj %>%
    st_as_sf(coords = c(x_mp, y_mp), crs = 3035) %>%
    st_buffer(dist = size/2, endCapStyle = "SQUARE")
}

get_breitband_stadt("Darmstadt", variables = down_fn_hh_ftthb_1000) %>%
  add_laea_grid() %>%
  ggplot()+
  geom_sf(aes(fill = down_fn_hh_ftthb_1000))
```

# Plots

```{r}
get_breitband_stadt("Berlin", variables = down_fn_hh_ftthb_1000) %>%
  filter(date == 202312) %>%
  add_laea_grid() %>%
  ggplot()+
  geom_sf(aes(fill = down_fn_hh_ftthb_1000), color = NA)+
  scale_fill_viridis_c()+
  theme_void()

get_breitband_stadt("Berlin", variables = down_fn_hh_ftthb_1000) %>%
  filter(date %in% c(202312, 202206)) %>%
  arrange(x_mp, y_mp, date) %>%
  group_by(x_mp, y_mp) %>%
  mutate(delta = down_fn_hh_ftthb_1000 - lag(down_fn_hh_ftthb_1000, n = 1)) %>%
  ungroup() %>%
  filter(date == 202312) %>%
  add_laea_grid() %>%
  ggplot()+
  geom_sf(aes(fill = delta), color = NA)+
  scale_fill_viridis_c()+
  theme_void()
```

Ganz Deutschland mit 1km Quadraten
```{r}
p <- breitband_1km_arrow %>%
  filter(date == 202312) %>%
  select(date, x_mp, y_mp, down_fn_hh_ftthb_1000) %>%
  collect() %>%
  add_laea_grid(size = 1000) %>%
  ggplot()+
  geom_sf(aes(fill = down_fn_hh_ftthb_1000), color = NA)+
  scale_fill_viridis_c()+
  theme_void()+
  theme(legend.position = "none")

ggsave("./Output/plot_de_glasfaser_1km.pdf", plot = p, width = 10, height = 20)
```

# Regression

Regression um Anteil Glasfaser durch die Zensus Daten zu erklären

```{r}
# Bestimmte Stadt
get_breitband_stadt("Berlin", variables = down_fn_hh_ftthb_1000) %>%
  filter(date %in% c(202312, 202206)) %>%
  arrange(x_mp, y_mp, date) %>%
  group_by(x_mp, y_mp) %>%
  mutate(delta = down_fn_hh_ftthb_1000 - lag(down_fn_hh_ftthb_1000, n = 1)) %>%
  ungroup() %>%
  filter(date == 202312) %>%
  left_join(zensus_beispiel, by = join_by(x_mp, y_mp)) %>%
  lm(delta ~ insgesamt_bevoelkerung + durchschnittsalter + eigentuemerquote + durchschn_miete_qm, data = .) %>%
  summary()

# Ganz Deutschland
breitband_100m_arrow %>%
  select(date, x_mp, y_mp, down_fn_hh_ftthb_1000) %>%
  filter(date %in% c(202312, 202206)) %>%
  arrange(x_mp, y_mp, date) %>%
  to_duckdb() %>%
  group_by(x_mp, y_mp) %>%
  mutate(delta = down_fn_hh_ftthb_1000 - lag(down_fn_hh_ftthb_1000, n = 1)) %>%
  ungroup() %>%
  filter(date == 202312) %>%
  collect() %>%
  left_join(zensus_beispiel, by = join_by(x_mp, y_mp)) %>%
  lm(delta ~ insgesamt_bevoelkerung + durchschnittsalter + eigentuemerquote + durchschn_miete_qm, data = .) %>%
  summary()
```

