[project]
name = "masterthesis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "pip>=25.0.1",
    "plotnine>=0.14.5",
    "polars>=1.23.0",
]
